### ISSUE TITLE
java.lang.RuntimeException: OJalgo dependency is missing [CBT build]

### ISSUE THREAD

**Issue by bbarker** [vagmcs/Optimus#18]
I'm using CBT to build [this project](https://github.com/CornellCAC/CobraScales) that uses Optimus; this is the first time I've seen an error like this, and I've used CBT a few times before, but I'm not highly confident that the issue isn't with CBT, or, perhaps both CBT and Optimus doing something out of the ordinary:

```
java.lang.RuntimeException: OJalgo dependency is missing.                                                                                                                           
        at scala.sys.package$.error(package.scala:27)                                                                                                                               
        at optimus.optimization.SolverFactory$.instantiate(LQModel.scala:57)                                                                                                        
        at optimus.optimization.LQProblem.instantiateSolver(LQModel.scala:70)                                                                                                       
        at optimus.optimization.AbstractMPProblem.solver$lzycompute(AbstractMPModel.scala:200)                                                                                      
        at optimus.optimization.AbstractMPProblem.solver(AbstractMPModel.scala:200)                                                                                                 
        at optimus.optimization.AbstractMPProblem.start(AbstractMPModel.scala:256)                                                                                                  
        at optimus.optimization.package$.start(package.scala:76)                                                                                                                    
        at cobrascales.optimization.OptimusCS$$anonfun$optimusTests$1.apply$mcV$sp(OptimusCS.scala:18)                                                                              
        at cobrascales.TestTry$.apply(TestTry.scala:13)                                                                                                                             
        at cobrascales.optimization.OptimusCS$.optimusTests(OptimusCS.scala:16)                                                                                                     
        at cobrascales.optimization.package$.optimizationTests(package.scala:12)                                                                                                    
        at cobrascales.Main$.main(Main.scala:13)                                                                                                                                    
        at cobrascales.Main.main(Main.scala)                                                                                                                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                         
        at cbt.reflect.Module$$anonfun$typeStaticMethod$1$$anonfun$apply$6.apply(reflect.scala:170)                                                                                 
        at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1$$anonfun$apply$2.apply(reflect.scala:121)                                                                       
        at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1$$anonfun$apply$2.apply(reflect.scala:121)                                                                       
        at cbt.reflect.Module$$anon$1.run(reflect.scala:178)                                                                                                                        
        at cbt.reflect.Module$$anon$1.run(reflect.scala:177)                                                                                                                        
        at cbt.reflect.TrapSystemExit.run(TrapSystemExit.java:15)                                                                                                                   
        at cbt.reflect.Module$class.trapExitCodeOrValue(reflect.scala:176)                                                                                                          
        at cbt.Stage1Lib.trapExitCodeOrValue(Stage1Lib.scala:14)                                                                                                                    
        at cbt.reflect.Module$class.trapExitCode(reflect.scala:185)                                                                                                                 
        at cbt.Stage1Lib.trapExitCode(Stage1Lib.scala:14)                                                                                                                           
        at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1.apply(reflect.scala:121)                                                                                        
        at cbt.reflect.Module$$anonfun$findStaticExitMethodOrFail$1.apply(reflect.scala:121)                                                                                        
        at cbt.reflect.Module$$anonfun$getMain$1.apply(reflect.scala:70)                                                                                                            
        at cbt.reflect.Module$$anonfun$getMain$1.apply(reflect.scala:70)                                                                                                            
        at cbt.reflect.StaticMethod.apply(StaticMethod.scala:4)                                                                                                                     
        at cbt.DependencyImplementation$class.runMain(resolver.scala:82)                                                                                                            
        at cobrascales_build.test.Build.cbt$BaseBuild$$super$runMain(build.scala:3)                                                                                                 
        at cbt.BaseBuild$class.runMain(BasicBuild.scala:370)                                                                                                                        
        at cobrascales_build.test.Build.runMain(build.scala:3)                                                                                                                      
        at cbt.DependencyImplementation$class.runMain(resolver.scala:85)                                                                                                            
        at cobrascales_build.test.Build.runMain(build.scala:3)                                                                                                                      
        at cbt.BaseBuild$class.run(BasicBuild.scala:217)                                                                                                                            
        at cobrascales_build.test.Build.run(build.scala:3)                                                                                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                         
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11$$anonfun$apply$12.apply(Lib.scala:155)                                                       
        at cbt.reflect.Module$$anon$1.run(reflect.scala:178)                                                                                                                        
        at cbt.reflect.Module$$anon$1.run(reflect.scala:177)                                                                                                                        
        at cbt.reflect.TrapSystemExit.run(TrapSystemExit.java:15)                                                                                                                   
        at cbt.reflect.Module$class.trapExitCodeOrValue(reflect.scala:176)                                                                                                          
        at cbt.Stage1Lib.trapExitCodeOrValue(Stage1Lib.scala:14)                                                                                                                    
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11.apply(Lib.scala:155)                                                                         
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9$$anonfun$apply$11.apply(Lib.scala:153)                                                                         
        at scala.Option.map(Option.scala:146)                                                                                                                                       
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9.apply(Lib.scala:153)                                                                                           
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1$$anonfun$apply$9.apply(Lib.scala:150)                                                                                           
        at scala.Option.map(Option.scala:146)                                                                                                                                       
        at cbt.Lib$$anonfun$cbt$Lib$$callInternal$1.apply(Lib.scala:150)                                                                                                            
        at cbt.Lib$$anonfun$3.cbt$Lib$$anonfun$$g$1(Lib.scala:103)                                                                                                                  
        at cbt.Lib$$anonfun$3$$anonfun$apply$5.apply(Lib.scala:105)                                                                                                                 
        at cbt.Lib.cbt$Lib$$callInternal(Lib.scala:175)                                                                                                                             
        at cbt.Lib.getReflective(Lib.scala:143)                                                                                                                                     
        at cbt.Lib.callReflective(Lib.scala:106)                                                                                                                                    
        at cbt.Stage2$.run(Stage2.scala:35)                                                                                                                                         
        at cbt.Stage2.run(Stage2.scala)                                                                                                                                             
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                         
        at cbt.Stage1$.run(Stage1.scala:210)                                                                                                                                        
        at cbt.Stage1.run(Stage1.scala)                                                                                                                                             
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                            
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                    
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                         
        at cbt.NailgunLauncher.main(NailgunLauncher.java:123)                                            
```

I can verify I saw it download ojalgo dependencies once I added the appropriate solver dependencies:

```
$ cbt run                                                                                                                                                                           
(Note: nailgun not found. It makes CBT faster! Try 'brew install nailgun' or 'apt-get install nailgun'.)                                                                            
(Note: nc not found. It will make slightly startup faster.)                                                                                                                         
Compiling to /home/brandon/workspace/CobraScales/build/target/scala-2.11/classes                                                                                                    
[info] Compiling 1 Scala source to /home/brandon/workspace/CobraScales/build/target/scala-2.11/classes...                                                                           
[info] Compile success at Feb 25, 2018 4:47:28 PM [2.259s]                                                                                                                          
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-oj_2.11/2.1.0/optimus-solver-oj_2.11-2.1.0.pom.sha1                                                     
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-oj_2.11/2.1.0/optimus-solver-oj_2.11-2.1.0.pom                                                          
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-gurobi_2.11/2.1.0/optimus-solver-gurobi_2.11-2.1.0.pom.sha1                                             
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-gurobi_2.11/2.1.0/optimus-solver-gurobi_2.11-2.1.0.pom                                                  
downloading https://repo1.maven.org/maven2/org/ojalgo/ojalgo/41.0.0/ojalgo-41.0.0.pom.sha1                                                                                          
downloading https://repo1.maven.org/maven2/org/ojalgo/ojalgo/41.0.0/ojalgo-41.0.0.pom                                                                                               
downloading https://repo1.maven.org/maven2/org/ojalgo/ojalgo/41.0.0/ojalgo-41.0.0.jar.sha1                                                                                          
downloading https://repo1.maven.org/maven2/org/ojalgo/ojalgo/41.0.0/ojalgo-41.0.0.jar                                                                                               
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-gurobi_2.11/2.1.0/optimus-solver-gurobi_2.11-2.1.0.jar.sha1                                             
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-gurobi_2.11/2.1.0/optimus-solver-gurobi_2.11-2.1.0.jar                                                  
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-oj_2.11/2.1.0/optimus-solver-oj_2.11-2.1.0.jar.sha1                                                     
downloading https://repo1.maven.org/maven2/com/github/vagmcs/optimus-solver-oj_2.11/2.1.0/optimus-solver-oj_2.11-2.1.0.jar                                                          
Compiling to /home/brandon/workspace/CobraScales/target/scala-2.11/classes     
```

** To reproduce **

1. Clone [CBT](https://github.com/cvogt/cbt), and add `/path/to/cbt` to the `PATH`, or call `/path/to/cbt/cbt` directly below.
2. Clone [the repo](https://github.com/CornellCAC/CobraScales) (fairly tiny)
3. cd to `CobraScales/test`
4. run `cbt run`

**Comment by cvogt** [comment]
@bbarker in your build try `override def flatClassLoader = true`. This disables some caching, but allows libraries to break out of their own dependencies, which some reflection magic requires.

**Comment by bbarker** [comment]
@cvogt awesome, that fixed it!

**Comment by cvogt** [comment]
@bbarker maybe should document this somewhere more visible?

**Comment by bbarker** [comment]
@cvogt would it be worth adding a note to the readme, or maybe on the wiki at https://github.com/cvogt/cbt/wiki/classloader-notes (note I can't edit the wiki)

**Comment by cvogt** [comment]
gave you edit rights to the wiki @bbarker
